### ISSUE TITLE
Inconsistent results to std out with simple recipe standing query on startup using FileIngest

### ISSUE THREAD

**Issue by qikijames** [thatdot/quine#43]
**Describe the bug**
I am trying out Quine on my laptop and seeing some inconsistent results that might be related to recipe startup sequencing. I have a recipe with a single FileIngest ingest stream and a single standing query that prints to standard out. Across multiple executions, I see different number of results, from 0 to 4 (expected). 

```
‹main●›
╰─$ java -jar quine-1.7.3.jar -p 8282 -r simple.yaml --recipe-value in_file=devices.json                                          130 ↵
Graph is ready
Running Standing Query STANDING-1
Running Ingest Stream INGEST-1
2024-11-17 21:59:13,910 Standing query `destination` match: {"meta":{"isPositiveMatch":true},"data":{"message":">>> id-4"}}
2024-11-17 21:59:13,912 Standing query `destination` match: {"meta":{"isPositiveMatch":true},"data":{"message":">>> id-2"}}
2024-11-17 21:59:13,912 Standing query `destination` match: {"meta":{"isPositiveMatch":true},"data":{"message":">>> id-3"}}
2024-11-17 21:59:13,913 Standing query `destination` match: {"meta":{"isPositiveMatch":true},"data":{"message":">>> id-1"}}
INGEST-1 status is completed and ingested 4
Quine web server available at http://127.0.0.1:8282
^CQuine is shutting down...
Shutdown complete.
‹main●›
╰─$ java -jar quine-1.7.3.jar -p 8282 -r simple.yaml --recipe-value in_file=devices.json                                          130 ↵
Graph is ready
Running Standing Query STANDING-1
Running Ingest Stream INGEST-1
2024-11-18 09:49:19,319 Standing query `destination` match: {"meta":{"isPositiveMatch":true},"data":{"message":">>> id-4"}}
INGEST-1 status is completed and ingested 4
Quine web server available at http://127.0.0.1:8282
^CQuine is shutting down...
Shutdown complete.
‹main●›
╰─$ java -jar quine-1.7.3.jar -p 8282 -r simple.yaml --recipe-value in_file=devices.json                                          130 ↵
Graph is ready
Running Standing Query STANDING-1
Running Ingest Stream INGEST-1
2024-11-18 09:49:38,036 Standing query `destination` match: {"meta":{"isPositiveMatch":true},"data":{"message":">>> id-1"}}
2024-11-18 09:49:38,039 Standing query `destination` match: {"meta":{"isPositiveMatch":true},"data":{"message":">>> id-4"}}
2024-11-18 09:49:38,040 Standing query `destination` match: {"meta":{"isPositiveMatch":true},"data":{"message":">>> id-3"}}
INGEST-1 status is completed and ingested 4
Quine web server available at http://127.0.0.1:8282
^CQuine is shutting down...
Shutdown complete.
```

**To Reproduce**
1. Recipe file: simple.yaml

```
version: 1
title: Ingest
contributor: https://github.com/qikijames
summary: Ingest example file of devices as graph
description: Ingests each line in "$in_file"
ingestStreams:
  - type: FileIngest
    path: $in_file
    format:
      type: CypherJson
      query: |-
        MATCH (m),(d)
        WHERE id(m) = idFrom("message", $that.msg_id, $that.customer_id)
          AND id(d) = idFrom("device", $that.id, $that.customer_id)
        SET m = $that,
            m.type = "message",
            m: message
        SET d.id = $that.id,
            d.ips = $that.ips,
            d.type = "device",
            d: device

        CREATE (m)-[:DEV]->(d)
standingQueries:
  - pattern:
      type: Cypher
      query: MATCH (m:message) RETURN DISTINCT id(m) AS id
    outputs:
      destination:
        type: CypherQuery
        query: |-
          MATCH (m1)-[:DEV]->(:device)
          WHERE id(m1) = $that.data.id
          RETURN '>>> ' + m1.id AS message
        andThen:
          type: PrintToStandardOut
nodeAppearances: [ ]
quickQueries: [ ]
sampleQueries: [ ]
```

2. Input file: devices.json

```
{ "msg_id":"m-1", "customer_id":"c-1", "id":"id-1", "cloud_id":"i-1", "ips":["1.1.1.1","2.2.2.2","3.3.3.3"], "hostname":"BP-111.local"}
{ "msg_id":"m-2", "customer_id":"c-1", "id":"id-2", "cloud_id":"i-2", "ips":["2.2.2.2"], "hostname":"BP-222.local"}
{ "msg_id":"m-3", "customer_id":"c-2", "id":"id-3", "cloud_id":"i-1", "ips":["1.1.1.1"], "hostname":"BP-999.local"}
{ "msg_id":"m-4", "customer_id":"c-1", "id":"id-4", "cloud_id":"i-1", "ips":["1.1.1.1","2.2.2.2","3.3.3.3"], "hostname":"BP-111"}
```

3. CLI execution

```
 java -jar quine-1.7.3.jar -p 8282 -r simple.yaml --recipe-value in_file=devices.json
```

**Expected behavior**
Consistent results of 4 messages printed to standard out.

**Desktop:**
 - OS: macOS
 - Version: Sonoma 14.5

**Additional context**
When the standing query output is changed from `MATCH (m1)-[:DEV]->(:device)` to `Match (m1)` I see 4 lines printed to standard out consistently.

For full context, I started with a more complex streaming entity resolution example and never saw any output to standard out. I ran the match query in the UI and it worked so it seemed really odd Eventually I simplified enough to start seeing output. 

Bonus points. If anybody can share the streaming entity resolution example that was demoed recently. :)

**Comment by rrwright** [comment]
HI @qikijames Thanks for the great repro instructions! Looks like it isn't a bug (but maybe a bug in our docs). What's happening is: since updates are done in parallel, the simpler `pattern` of the standing query is matching and triggering the more complex output query before the whole pattern exists. In essence: it's matching too fast. So the `outputs` query runs before the full structure is completed in the data. If you include in the standing query pattern the full structure of what you want to find, then you should see all 4 results produced consistently (though the order might change because of parallel processing/matching.

Example:
Change the standing query line 27 to:
```
query: MATCH (m:message)-[:DEV]->(:device) RETURN DISTINCT id(m) AS id
```

**Comment by bkyrlach** [comment]
Hey @qikijames...

To go into a little more detail,  I think the issue here might be due to a mental model mismatch. Quine utilizes a node-centric model of computation, which has a lot of implications for how your ingest, standing query, and output query interact with each other.

In your ingest query, you create a `message` node and a `device` node and create an edge between them. Note, that unlike traditional database tools you might have used in the past, this ingest query will be eventually consistent. That means that there could be a point in time in the processing of a record from your ingest file that only the `message` node exists, or only the `device` node.

Your standing query matches on `message` nodes, and reports their distinct ids. This is the input to your output query, and the place where we can sometimes observe graph states that haven't reached that "eventual" consistency. Your output query will only match `message` nodes that have an outgoing `DEV` edge to a device node, where the id of the `message` node is the id returned by your standing query. Since your standing query can match on the `message` node as soon as it's created, this match might get processed by the output query before the relevant `device` node and `DEV` edge are added.

This is actually the correct (albeit perhaps a little unintuitive at first) behavior. Your ingest query will eventually result in the desired graph state you want. However, your standing query is underspecified. The current standing query you have defined will immediately match on intermediate graph states (i.e. where the `message` node is created, but the `device` node and/or `DEV` edge have not yet been created). This immediately feeds into your output query which, as currently structured, attempts to match the expected end state of the graph (i.e. `message` node connected to `device` node via a `DEV` edge). If this state isn't the current state of the graph, then your output query will fail to output one or more expected results.

The simplest fix here is to change your standing query. If you put the fully desired graph pattern in your standing query, you'll see the expected results. That is, change your standing query to...

```MATCH (m:message)-[:DEV]->(:device) RETURN DISTINCT id(m) AS id```

However, I think even in your minimal reproduction, I might choose to do even more work in my standing query. By using a multiple-values standing query, you can actually have your standing query extract the interesting data from your graph, which then removes the need for an output query entirely.

I hope that this explanation helps, and please feel free to followup with any questions or comments!

Oh, one last thing! Our user community on [discord](https://discord.gg/2RfkDu96UN) is a great place to ask these sorts of questions!

**Comment by qikijames** [comment]
Ah, that makes sense. Thank you for the quick responses!
